development:
  reconnect: true
  adapter: mysql2
  encoding: utf8
  database: freelanceProject
  pool: 5
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
production:
  reconnect: true
  adapter: mysql2
  encoding: utf8
  database: wikiruby
  pool: 5
  username: adminvLpRksZ
  password: mxS4hnfKQQFC
  host: 127.7.20.130:3306